package notification

enum NotificationFlowState {
  START,
  INFORMATION_REQUESTED_FROM_AGENT,
  SURVEY_REQUESTED_FROM_CONSUMER,
  SURVEY_COMPLETED_BY_CONSUMER,
  SURVEY_REVIEWED_BY_AGENT,
  SURVEY_RELEASED_BY_ADMIN
}

